### ISSUE TITLE
On Adjusting Clock Settings

### ISSUE THREAD

**Issue by StephanieML** [homermultitext/hmt-docs#10]
If you right-click on the time, you can access "Digital Clock" Settings.

This is where it gets tricky, because you have to enter the code for the representation you want. I found a cheatsheet here: http://php.net/manual/en/function.strftime.php. 

I don't know how much information we want to overload people with. The default setting uses the time on your host machine, I think.

**Comment by StephanieML** [comment]
Referenced on this page: http://homermultitext.github.io/hmt-docs/vm/

**Comment by neelsmith** [comment]
Maybe put this in a reference section -- not part of their walkthrough for installation, but available for troubleshooting?

**Comment by StephanieML** [comment]
Sounds good to me.

**Comment by neelsmith** [comment]
Or maybe not worry about it in 2016 -- new VM may be smart enough about time that we no longer have to worry about this.  We should test this before closing issue by getting someone _outside_ US Eastern time to build the VM and see if the timezone comes up correctly.

**Comment by neelsmith** [comment]
Closing out as issue for hmt-docs:  keeping these notes in a separate file in case we need to deal with Ubuntu time settings again.
