### ISSUE TITLE
Dead Links On the Summer Seminar Page

### ISSUE THREAD

**Issue by StephanieML** [homermultitext/hmt-docs#23]
- from summer seminar home page (http://homermultitext.github.io/summerseminar2016/):
  - http://homermultitext.github.io/summerseminar2016/git
- from reference page (http://homermultitext.github.io/summerseminar2016/references/):
  - http://homermultitext.github.io/summerseminar2016/references/faq
  - http://homermultitext.github.io/summerseminar2016/palguide.pdf

**Comment by neelsmith** [comment]
closing
