### ISSUE TITLE
Missing Links

### ISSUE THREAD

**Issue by StephanieML** [homermultitext/hmt-docs#6]
On: http://homermultitext.github.io/hmt-docs/vm/

under: 'Using the VM', there is a bullet for typing accented Greek, and I'm fairly certain Chris has a couple helpful links on the summer seminar page

**Comment by neelsmith** [comment]
I've got Chris' page in the "Tips" section, but it doesn't deal with typing Greek in the VM's polytonic Greek font.

I've got some notes I need to move over for this link.

**Comment by neelsmith** [comment]
Updated for 2016 VM.  Closing out.  If we need to cross link tips for typing on Mac and Windows with docs on typing in the VM, we should make that a separate issue.
