### ISSUE TITLE
Awkward Wording

### ISSUE THREAD

**Issue by StephanieML** [homermultitext/hmt-docs#8]
Here: http://homermultitext.github.io/hmt-docs/tips/pasteboard/

Original: We use several Unicode combining characters for accents, etc., that modify a preceding to character to form a single composite. We will gradually add a list of those here for editors who cannot easily use enter those from their keyboard layout.

Suggested Revision: We use several Unicode combining characters for accents, etc., that modify a preceding character to for a single composite. We will gradually ad a list of those here for editors who cannot easily enter from their keyboard layout to use.

**Comment by neelsmith** [comment]
done
